services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    command: npx nodemon -L --inspect=0.0.0.0:9229 server.js -- -h 0.0.0.0 -p 8081 -c ./cache
    volumes:
      - .:/usr/src/app  
    ports:
      - 8081:8081
      - 9229:9229


